// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPeDhY0ib00-zVofqVxHUGEl9ta83552c',
    appId: '1:1022288201597:web:51adf80f7e6b217fd2ae14',
    messagingSenderId: '1022288201597',
    projectId: 'finwise-e4c7a',
    authDomain: 'finwise-e4c7a.firebaseapp.com',
    storageBucket: 'finwise-e4c7a.firebasestorage.app',
    measurementId: 'G-KX3D8RZW4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkMNgmYbXUZgiPHqNQ7CHUhELEMckNwUU',
    appId: '1:1022288201597:android:b082f6bebf11e3b7d2ae14',
    messagingSenderId: '1022288201597',
    projectId: 'finwise-e4c7a',
    storageBucket: 'finwise-e4c7a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyeqxNxB7sy0JGJEJj1eiVe0WdE2ElAA',
    appId: '1:1022288201597:ios:29bfc9c024bf6314d2ae14',
    messagingSenderId: '1022288201597',
    projectId: 'finwise-e4c7a',
    storageBucket: 'finwise-e4c7a.firebasestorage.app',
    androidClientId: '1022288201597-jsmijavt7p6ptpo4pdl644td1caupf1t.apps.googleusercontent.com',
    iosClientId: '1022288201597-rtiviq8h6uouhbu4i68jqlu7rhbacmjg.apps.googleusercontent.com',
    iosBundleId: 'com.depi.finwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPeDhY0ib00-zVofqVxHUGEl9ta83552c',
    appId: '1:1022288201597:web:93e9746f1c400b57d2ae14',
    messagingSenderId: '1022288201597',
    projectId: 'finwise-e4c7a',
    authDomain: 'finwise-e4c7a.firebaseapp.com',
    storageBucket: 'finwise-e4c7a.firebasestorage.app',
    measurementId: 'G-YJYCLV7FQQ',
  );
}
